version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    ports:
    - "5672:5672" # Default RabbitMQ port; https://www.rabbitmq.com/networking.html
    - "8080:15672"

  minio:
    image: "minio/minio:RELEASE.2018-06-09T03-43-35Z"
    command: "server /data"
    volumes:
      - ./storage:/data
    ports:
    - "9000:9000"
