[[constraint]]
  branch = "master"
  name = "github.com/nareix/joy4"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.2"
