// DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
package main

import (
	"github.com/gorilla/mux"

	"github.com/NaurisSadovskis/sample-architecture-video-transcoder/api/handlers/transcodejob"
)

func initRoutes(r *mux.Router) {

	TranscodejobInterfaceRoutes(r, transcodejob.TranscodejobAPI{})
}
